### ISSUE TITLE
segmentation error

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#10]
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For
more information, click here. 
Warning: Directory already exists. 
> In segmentBeads_v0_1>segmentBeads_Callback (line 130)
  In gui_mainfcn (line 95)
  In segmentBeads_v0_1 (line 45)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('segmentBeads_Callback',hObject,eventdata,guidata(hObject)) 
Error using griddedInterpolant
The grid vectors do not define a grid of points that match the given values.

Error in interp3 (line 146)
            F = griddedInterpolant(X, Y, Z, V, method,extrap);

Error in segmentBeads_v0_1>segmentBeads_Callback (line 149)
    cutout=interp3(X,Y,Z,single(cutout_tmp),Xq,Yq,Zq);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('segmentBeads_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by bernhardw13** [comment]
I cannot reproduce this error. Can you give an example dataset and parameters used?
