### ISSUE TITLE
Error while opening segmentBeads_v0_1

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#3]
The following error appeared when I opened segmentBeads_v0_1:

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_0('listbox3_CreateFcn',hObject,eventdata,guidata(hObject)) 
Undefined function or variable 'segmentBeads_v0_0'.

Thanks for your help :)

**Comment by bernhardw13** [comment]
Hi, I fixed this bug. It came up because I created the new version by manual copying an older version in the file system. Instead one should create new versions by opening the gui in GUIDE and 'save as' new version. This automatically sets all dependencies/names correctly...
