### ISSUE TITLE
Error when loading tiff stack

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#4]
When opening the provided tiff-stack, following Matlab-error occurs. This error does not occur with other stacks.

```
Reference to non-existent field 'plotwindow'.

Error in segmentBeads_v0_1>plotBeadPos (line 511)
 hold(handles.plotwindow,'off');

Error in segmentBeads_v0_1>loadImage (line 499)
plotBeadPos(hObject, handles)

Error in segmentBeads_v0_1>OpenImage_Entry_Callback (line 450)
handles=loadImage(hObject,handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('OpenImage_Entry_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.
```

**Comment by bernhardw13** [comment]
The error occurs when one starts the GUI by doubleclicking the .fig-file. Then when one opens a tiff-stack the described message appears. It seems like the handles struct does not contain all fields. When one starts the GUI via running the script everything is fine. 
I have no clue what exactly the problem is here...

**Comment by bernhardw13** [comment]
After some research I found that 

> Double-clicking on a .fig file only does an openfig(), which would at most restore the figure to the saved state.

So actually you do not run the GUI properly when double clicking on it. In order for the GUI to work correctly either run the script or open it in GUIDE and run it there.
