### ISSUE TITLE
segmentation error

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#5]
Reference to non-existent field 'cutout'.

Error in segmentBeads_v0_1>segmentBeads_Callback (line 270)
handles.segframe.Max=size(handles.Beads(handles.currentBead).cutout,3);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('segmentBeads_Callback',hObject,eventdata,guidata(hObject)) 
270 handles.segframe.Max=size(handles.Beads(handles.currentBead).cutout,3);
K>>

**Comment by bernhardw13** [comment]
Error fixed: It was related to the situation when a cutout box exceeds over the dimensions of the stack. Now I implemented a better handling of this situation, i.e. dimensions of a cutout box are automatically limited by dimensions of the stack.
