### ISSUE TITLE
segmentation failure

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#6]
Error using wtifc
TIFF library error - 'TIFFAppendToStrip:  Maximum TIFF file size exceeded.'

Error in writetif (line 110)
wtifc(data, map, filename, writemode, colorspace, required_tags);

Error in imwrite (line 485)
        feval(fmt_s.write, data, map, filename, paramPairs{:});

Error in segmentBeads_v0_1>segmentBeads_Callback (line 178)
        imwrite(uint16(filtered(:,:,l)),horzcat(save_dir,filesep,'FilteredBead',num2str(noBeads),'.tif'),'writemode','append');
        
Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('segmentBeads_Callback',hObject,eventdata,guidata(hObject)) 
488         rethrow(myException);
K>>

**Comment by bernhardw13** [comment]
It seems like `imwrite` only supports tiff files <4GB, i.e. it does not support BigTiff. I will work on incorporation of BigTiff into the GUI.

**Comment by bernhardw13** [comment]
Should be solved with last commit :)
