### ISSUE TITLE
calc stress error

### ISSUE THREAD

**Issue by ArneHofemeier** [bernhardw13/BeadSegmentation#8]
Undefined variable "ModelUtil" or class "ModelUtil.create".

Error in calcStress (line 10)
model = ModelUtil.create(modelname);

Error in segmentBeads_v0_1>calcforce_Callback (line 880)
model=calcStress(2100,0.49,1000,r,horzcat(displacementfiles(j).folder,filesep,displacementfiles(j).name),modeltag);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in segmentBeads_v0_1 (line 45)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)segmentBeads_v0_1('calcforce_Callback',hObject,eventdata,guidata(hObject)) 
10  model = ModelUtil.create(modelname);

**Comment by bernhardw13** [comment]
Are you sure, that you connected MATLAB to comsol server and included the matlab files of comsol (folder and subfolders of /usr/local/comsol53a/multiphysics/mli/)?

**Comment by bernhardw13** [comment]
Since I didn't hear anything anymore, I consider this closed. Thanks!
